#!/bin/sh
#
# Probe for the installed TCL version.
# This is put into an extra file because of M4 interpreting the brackets ... ;-(

if [ $# -gt 1 ]; then
    tcl_version=`$1/tcl -c "puts [info tclversion]"`
else
    tcl_version=`tcl -c "puts [info tclversion]"`
fi

echo $tcl_version
