#!/bin/sh
CFLAGS=-g
LDFLAGS=-g
CC=gcc
export CFLAGS LDFLAGS CC
#TCLTKROOT=/usr/local/tcltk/8.0.5
#export TCLTKROOT

./configure \
		--prefix=/usr/local/Modules/@VERSION@ \
		--with-module-path=/usr/local/Modules/modulefiles \
		--with-version-path=/usr/local/Modules/versions \
		--with-etc-path=/etc \
		--with-skel-path=/etc/skel \
		--with-split-size=960
exit

		--enable-free \
# the above values for
#	--with-module-path, --with-version-path,
#	--with-etc-path, --with-skel-path
# are default values and are here for pedagogical purposes
