%global macrosdir %(d=%{_rpmconfigdir}/macros.d; [ -d $d ] || d=%{_sysconfdir}/rpm; echo $d)
# define license macro for el6 build
%{!?_licensedir:%global license %%doc}

Name:           modules-tcl
Version:        1.775
Release:        1%{?dist}
Summary:        Native Tcl version of the Environment Modules system

Group:          System Environment/Base
License:        GPLv2+
URL:            http://modules.sourceforge.net/
Source0:        http://downloads.sourceforge.net/modules/%{name}-%{version}.tar.gz
Source1:        macros.%{name}
# the 3 following patches will be included in next upstream release
Patch0:         %{name}-1.775-no-html-doc-build.patch
Patch1:         %{name}-1.775-xres-no-display-err.patch
Patch2:         %{name}-1.775-switchml-path-reset.patch

BuildArch:      noarch
BuildRequires:  tcl
BuildRequires:  dejagnu
BuildRequires:  perl
%if 0%{?fedora} || (0%{?rhel} && 0%{?rhel} > 6)
BuildRequires:  perl-podlators
%endif
%if 0%{?rhel} && 0%{?rhel} <= 6
BuildRequires:  net-tools
%else
BuildRequires:  hostname
%endif
Requires:       tcl
Requires:       sed
%if 0%{?rhel} && 0%{?rhel} <= 6
Requires:       procps
Requires:       man
Requires:       net-tools
%else
Requires:       procps-ng
Requires:       man-db
Requires:       hostname
%endif
Requires(post): coreutils
Requires(post): %{_sbindir}/update-alternatives
Requires(postun): %{_sbindir}/update-alternatives
Provides:       environment(modules)

%description
The Environment Modules package is a tool that simplify shell initialization
and lets users easily modify their environment during the session with
modulefiles. Modules-Tcl is the full Tcl rewrite of the Modules package.

Each modulefile contains the information needed to configure the shell for
an application. Once the Modules package is initialized, the environment can
be modified on a per-module basis using the module command which interprets
modulefiles. Typically modulefiles instruct the module command to alter or
set shell environment variables such as PATH, MANPATH, etc. modulefiles may
be shared by many users on a system and users may have their own collection
to supplement or replace the shared modulefiles.

Modules can be loaded and unloaded dynamically and atomically, in an clean
fashion. All popular shells are supported, including bash, ksh, zsh, sh,
csh, tcsh, fish, as well as some scripting languages such as perl and python.

Modules are useful in managing different versions of applications. Modules
can also be bundled into metamodules that will load an entire suite of
different applications.

%prep
%setup -q
%patch0 -p1 -b .nohtmldoc
%patch1 -p1 -b .xresnodis
%patch2 -p1 -b .swmlpath

%build
# configure script for this software is not generated by autoconf
./configure --prefix=%{_datadir}/%{name} \
            --bindir=%{_bindir} \
            --with-modulepath=%{_sysconfdir}/modulefiles:%{_datadir}/modulefiles \
            --with-cver-initdir=%{_datadir}/Modules/init
make %{?_smp_mflags}

%check
make test

%install
make install DESTDIR=%{buildroot}

# comply with other environment-modules packages modulefiles directory definition
mkdir -p %{buildroot}%{_sysconfdir}/modulefiles
mkdir -p %{buildroot}%{_datadir}/modulefiles

mkdir -p %{buildroot}%{_sysconfdir}/profile.d
%if 0%{?fedora}
# setup for alternatives on Fedora
touch %{buildroot}%{_sysconfdir}/profile.d/modules.{csh,sh}
%else
# install profile links to override environment-modules
ln -s %{_datadir}/%{name}/init/profile.csh %{buildroot}%{_sysconfdir}/profile.d/t00_modules-tcl.csh
ln -s %{_datadir}/%{name}/init/profile.sh %{buildroot}%{_sysconfdir}/profile.d/t00_modules-tcl.sh
%endif

# install the rpm config file an environment-modules flavor should provide
install -Dpm 644 %{SOURCE1} %{buildroot}/%{macrosdir}/macros.%{name}

# remove doc installed by make, use doc and license macros in files section
rm -rf %{buildroot}%{_datadir}/%{name}/share/doc

%if 0%{?fedora}
%post
# cleanup from pre-alternatives
if [ ! -L %{_sysconfdir}/profile.d/modules.sh ] ; then
  rm -f %{_sysconfdir}/profile.d/modules.sh
fi
%{_sbindir}/update-alternatives \
  --install %{_sysconfdir}/profile.d/modules.sh modules.sh %{_datadir}/%{name}/init/profile.sh 10 \
  --slave %{_sysconfdir}/profile.d/modules.csh modules.csh %{_datadir}/%{name}/init/profile.csh

%postun
if [ $1 -eq 0 ] ; then
  %{_sbindir}/update-alternatives --remove modules.sh %{_datadir}/%{name}/init/profile.sh
fi
%endif

%files
%license COPYING.GPLv2
%doc ChangeLog NEWS README.txt doc/diff_with_c-version.txt
%{_sysconfdir}/modulefiles
%if 0%{?fedora}
%ghost %{_sysconfdir}/profile.d/modules.csh
%ghost %{_sysconfdir}/profile.d/modules.sh
%else
%{_sysconfdir}/profile.d/t00_modules-tcl.csh
%{_sysconfdir}/profile.d/t00_modules-tcl.sh
%endif
%{_bindir}/envml
%dir %{_datadir}/%{name}
%dir %{_datadir}/%{name}/libexec
%{_datadir}/%{name}/libexec/modulecmd.tcl
%dir %{_datadir}/%{name}/init
# follow same configuration approach than environment-modules
%config(noreplace) %{_datadir}/%{name}/init/*
# man pages left in software-specific share dir not to conflict with
# environment-modules (will see with environment-modules maintainer if
# possible to use alternatives for these man pages)
%dir %{_datadir}/%{name}/share
%{_datadir}/%{name}/share/man
%{_datadir}/modulefiles
%{macrosdir}/macros.%{name}

%changelog
* Tue Mar  7 2017 Xavier Delaruelle <xavier.delaruelle@cea.fr> - 1.775-1
- Initial packaging.

