##############################################################################
#   Modules Revision 3.0
#   Providing a flexible user environment
#
#   File:		modules.70-maint/%M%
#   Revision:		%I%
#   First Edition:	1995/12/06
#   Last Mod.:		%U%, %G%
#
#   Authors:		Jens Hamisch, Jens.Hamisch@Strawberry.COM
#
#   Description:	Testuite testsequence
#   Command:		purge
#   Modulefiles:	setenv/1.0
#   Sub-Command:
#
#   Comment:	%C{
#			Tests the module command 'purge'
#		}C%
#
##############################################################################

#
#  Variables. This test forces a module load command. It will result in the
#    environment variables "_LMFILES_", "LOADEDMODULES" and "testsuite" to
#    be set up
#

set module "setenv/1.0"
set modulefile "$modpath/$module"

#
#  Check this only fo the /bin/csh
#

lappend ans [list unset testsuite]
lappend ans [list unsetpath LOADEDMODULES]
lappend ans [list unsetpath _LMFILES_]

#
#  Set up the environment pointing to the single module file being load
#

set env(_LMFILES_) $modulefile
set env(LOADEDMODULES) $module

#
#  The tests
#

test_cmd "csh" "purge" $ans


# setup LOADEDMODULES with an empty element
set env(LOADEDMODULES) ":$module"

set ans [list]
lappend ans [list unset testsuite]
# empty elements are ignored but stick to the variable, they should be removed
lappend ans [list setpath LOADEDMODULES ""]
lappend ans [list unsetpath _LMFILES_]

test_cmd "sh" "purge" $ans

# restore LOADEDMODULES
set env(LOADEDMODULES) "$module"


#
#  Cleanup
#

unset env(LOADEDMODULES)
unset env(_LMFILES_)

unset ans

unset modulefile
unset module
