##############################################################################
#   Modules Revision 3.2.8
#   Providing a flexible user environment
#
#   First Edition:	2010/09/13
#
#   Authors:		R.K. Owen, rk@owen.sj.ca.us
#
#   Description:	Deep modulefile directories
#
##############################################################################

if [info exists env(TESTSUITEDIR)] {
    set	saved_modpath	"$env(MODULEPATH)"
    set	modpath	"$env(TESTSUITEDIR)/modulefiles.deep"
    set	env(MODULEPATH)	"$env(TESTSUITEDIR)/modulefiles:$modpath"
    if { $verbose > 0 } {
	send_user "\tSetup MODULEPATH ... $env(MODULEPATH)\n"
    }
} else {
    send_user "\n\n\nFATAL: Please set the TESTSUITEDIR env var first\n\n\n"
    exit
}

set cplain	"plain"
set iplain0	"plain"
set oplain0	"plain/dir2/2.0"
set iplain1	"plain/dir1"
set oplain1	"plain/dir1/2.0"

set cmodulerc	"modulerc"
set imodulerc0	"modulerc"
set omodulerc0	"modulerc/dir1/1.0"
set imodulerc1	"modulerc/dir2"
set omodulerc1	"modulerc/dir2/1.0/rc1"
set imodulerc2	"modulerc/dir2/2.0"
set omodulerc2	"modulerc/dir2/2.0"

set cversion	"version"
set iversion0	"version"
set oversion0	"version/dir1/1.0"
set iversion1	"version/dir2"
set oversion1	"version/dir2/2.0/rc1"
set iversion2	"version/dir2/1.0"
set oversion2	"version/dir2/1.0"
