.\" RCSID @(#)$Id: iprime.man,v 1.1 2002/07/18 22:07:50 rkowen Exp $
.\" LIBDIR
.TH "IPRIME" "3rko" "09 Sep 1999"
.SH NAME
iprime \- finds the lowest prime factor
.SH SYNOPSIS

.nf
#include "iprime.h"

         char  chprime(char n);
  signed char  scprime(signed char n);
unsigned char  ucprime(unsigned char n);
         short  hprime(short n);
unsigned short uhprime(unsigned short n);
         int    iprime(int n);
unsigned int   uiprime(unsigned int n);
         long   lprime(long n);
unsigned long  ulprime(unsigned long n);
.fi

.SH DESCRIPTION
The
.I iprime
collection returns the lowest prime factor for the given
integer argument.  It straight forwardly searches from the
first few primes until it exhausts the look-up table.
After that it then tries the odd numbers
upto the sqrt of the argument.

.SH SEE ALSO
isqrt(3rko),gcd(3rko)

.SH DIAGNOSTICS
Returns 0 for invalid input values.

.SH AUTHOR
R.K.Owen,Ph.D.

.KEY WORDS
