##############################################################################
#   Modules Revision 3.0
#   Providing a flexible user environment
#
#   File:		modules.20-locate/%M%
#   Revision:		%I%
#   First Edition:	1995/12/06
#   Last Mod.:		%U%, %G%
#
#   Authors:		Jens Hamisch, Jens.Hamisch@Strawberry.COM
#
#   Description:	Testuite testsequence
#   Command:		load
#   Modulefiles:	loc_sym/alias1 loc_sym_alias2 loc_sym/alias3
#   Modulefiles:	loc_sym/alias4 loc_sym_alias5 loc_sym/alias6
#   Sub-Command:
#
#   Comment:	%C{
#			Check the 'module-alias' command
#		}C%
#
##############################################################################

#
#  Variables. This test forces a module load command. It will result in the
#    environment variables "_LMFILES_", "LOADEDMODULES" and "testsuite" to
#    be set up
#

set module_1 "loc_sym/alias1"
set modulefile_1 "$env(MODULEPATH)/$module_1"

set module_2 "loc_sym/alias2"
set modulefile_2 "$env(MODULEPATH)/$module_2"

set module_3 "loc_sym/alias3"
set modulefile_3 "$env(MODULEPATH)/$module_3"

set module_4 "loc_sym/alias4"
set modulefile_4 "$env(MODULEPATH)/$module_4"

set module_5 "loc_sym/alias5"
set modulefile_5 "$env(MODULEPATH)/$module_5"

set module_6 "loc_sym/alias6"
set modulefile_6 "$env(MODULEPATH)/$module_6"

set module_7 "loc_sym/alias7"
set modulefile_7 "$env(MODULEPATH)/$module_7"

#
#  Only checked for the csh
#

#
#  The tests
#

lappend ans [list set testsuite "loc_sym/1.0"]
lappend ans [list setpath LOADEDMODULES $module_1]
lappend ans [list setpath _LMFILES_ $modulefile_1]
test_cmd "csh" "load $module_1" $ans

set ans [list]
lappend ans [list set testsuite "loc_sym/2.0"]
lappend ans [list setpath LOADEDMODULES $module_2]
lappend ans [list setpath _LMFILES_ $modulefile_2]
test_cmd "csh" "load $module_2" $ans

set ans [list]
lappend ans [list set testsuite "loc_sym/1.0"]
lappend ans [list setpath LOADEDMODULES $module_3]
lappend ans [list setpath _LMFILES_ $modulefile_3]
test_cmd "csh" "load $module_3" $ans

set ans [list]
lappend ans [list set testsuite "loc_sym/2.0"]
lappend ans [list setpath LOADEDMODULES $module_4]
lappend ans [list setpath _LMFILES_ $modulefile_4]
test_cmd "csh" "load $module_4" $ans

set ans [list]
lappend ans [list set testsuite "loc_sym"]
lappend ans [list setpath LOADEDMODULES $module_5]
lappend ans [list setpath _LMFILES_ $modulefile_5]
test_cmd "csh" "load $module_5" $ans

set ans [list]
lappend ans [list set testsuite "loc_sym/1.0"]
lappend ans [list setpath LOADEDMODULES $module_6]
lappend ans [list setpath _LMFILES_ $modulefile_6]
test_cmd "csh" "load $module_6" $ans

set ans [list]
lappend ans [list set ts1 "loc_sym"]
lappend ans [list set ts2 "loc_sym/default"]
lappend ans [list set ts3 "loc_sym/1.0"]
lappend ans [list set ts4 "loc_sym/1.0"]
lappend ans [list setpath LOADEDMODULES $module_7]
lappend ans [list setpath _LMFILES_ $modulefile_7]
test_cmd "csh" "load $module_7" $ans

#
#  Cleanup
#

unset ans

unset modulefile_1
unset module_1
unset modulefile_2
unset module_2
unset modulefile_3
unset module_3
unset modulefile_4
unset module_4
unset modulefile_5
unset module_5
unset modulefile_6
unset module_6
unset modulefile_7
unset module_7
