#!/bin/sh
# fake Windows mode output

echo "
Status for device CON:
----------------------
    Lines:          9001
    Columns:        120
    Keyboard rate:  31
    Keyboard delay: 1
    Code page:      437

"
exit 0
