#!/bin/sh

cat << EOF

Sorry, cannot run the testsuite on your system!
In order to run the testsuite you have to: 

    1.)  Install dejagnu-1.2 or better
    2.)  Set up your PATH pointing to the 'runtest' binary
    3.)  rerun 'configure'
    4.)  make check

EOF
