#!/bin/sh
# fake Solaris stty output

echo "speed 38400 baud; -parity hupcl 
rows = 40; columns = 120; ypixels = 0; xpixels = 0;
eol = -^?; eol2 = -^?; swtch = <undef>; 
brkint -inpck -istrip icrnl imaxbel onlcr 
echo echoe echok echoctl echoke iexten "
exit 0
