##############################################################################
#   Modules Revision 3.0
#   Providing a flexible user environment
#
#   File:		modules.90-avail/%M%
#   Revision:		%I%
#   First Edition:	95/12/06
#   Last Mod.:		%U%, %G%
#
#   Authors:		Jens Hamisch, Jens.Hamisch@Strawberry.COM
#
#   Description:	Testuite testsequence
#   Command:		avail
#   Modulefiles:	setenv/1.0, loc_rc6/bar
#   Sub-Command:
#
#   Comment:	%C{
#			Check the module 'avail' command for a full qualified
#			module name in terse output mode.
#		}C%
#
##############################################################################

set module "setenv"
set version "1.0"
eval set [ array get env MODULEPATH ]
set module2 "loc_rc6"
set alias2 "bar"

#
#  Check this only fo the /bin/csh
#

set header "\[-\]+ $MODULEPATH \[-\]+\n"
set ts_csh "$header$module/$version"

#
#  The tests
#

testerr_cmd_re "csh" "avail $module/$version" "$ts_csh\\s+\$"
testerr_cmd_re "csh" "avail $module" "$ts_csh\\s+\$"

#
#  Test avail on an alias module
#

set ts_csh "$header$module2/$alias2\\(@\\)"
testerr_cmd_re "csh" "avail $module2/$alias2" "$ts_csh\\s+\$"

#
#  Cleanup
#

unset ts_csh
unset header
unset MODULEPATH
unset version
unset module
unset alias2
unset module2
