##############################################################################
#   Modules Revision 3.0
#   Providing a flexible user environment
#
#   File:		modules.50-cmds/%M%
#   Revision:		%I%
#   First Edition:	2018/04/07
#   Last Mod.:		%U%, %G%
#
#   Authors:		Xavier Delaruelle, xavier.delaruelle@cea.fr
#
#   Description:	Testuite testsequence
#   Command:		load, unload, display, help, test
#   Modulefiles:	append/7.0
#   Sub-Command:
#
#   Comment:	%C{
#           Check the effect of 'append-path' command on $env() array
#           variable through the different modulefile evaluation mode
#		}C%
#
##############################################################################

set module "append/7.0"
set modulefile "$modpath/$module"
set modulefilere "$modpathre/$module"

#
#  test load mode
#

set ans [list]
lappend ans [list setpath TS1 yes]
lappend ans [list set TS2 yes]
lappend ans [list setpath LOADEDMODULES $module]
lappend ans [list setpath _LMFILES_ $modulefile]
testouterr_cmd "sh" "load $module" $ans ""

# test with value set to variable prior to load
setenv_var TS1 "no"
set ans [list]
lappend ans [list setpath TS1 "no:yes"]
lappend ans [list set TS2 "no:yes"]
lappend ans [list setpath LOADEDMODULES $module]
lappend ans [list setpath _LMFILES_ $modulefile]
testouterr_cmd_re "sh" "load $module" $ans ""


#
#  test unload mode
#

# test with module loaded
setenv_path_var TS1 "yes"
setenv_var TS2 "yes"
setenv_loaded_module $module $modulefile

set ans [list]
lappend ans [list unsetpath TS1]
lappend ans [list unset TS2]
lappend ans [list unsetpath LOADEDMODULES]
lappend ans [list unsetpath _LMFILES_]
testouterr_cmd "sh" "unload $module" $ans ""

# test with module loaded but vanished env vars
unsetenv_path_var TS1
unsetenv_var TS2

set ans [list]
lappend ans [list unset TS1]
lappend ans [list unset TS2]
lappend ans [list unsetpath LOADEDMODULES]
lappend ans [list unsetpath _LMFILES_]
testouterr_cmd "sh" "unload $module" $ans ""

# test with module loaded but env var transformed as standard var (no path var)
# standard var is transformed as path var through unload evaluation
setenv_var TS1 "no"

set ans [list]
lappend ans [list setpath TS1 "no"]
lappend ans [list unset TS2]
lappend ans [list unsetpath LOADEDMODULES]
lappend ans [list unsetpath _LMFILES_]
testouterr_cmd "sh" "unload $module" $ans ""

# restore environment
unsetenv_loaded_module
unsetenv_var TS1


#
#  test display mode
#

set tserr "$modlin
$modulefilere:

append-path\tTS1 yes
setenv\t\tTS2 yes
$modlin"

# test without module loaded
testouterr_cmd_re "sh" "display $module" "" $tserr

# test with module loaded
setenv_path_var TS1 "yes"
setenv_var TS2 "yes"
setenv_loaded_module $module $modulefile

testouterr_cmd_re "sh" "display $module" "" $tserr

# restore environment
unsetenv_path_var TS1
unsetenv_var TS2
unsetenv_loaded_module


#
#  test help mode
#

set tserr "$modlin
Module Specific Help for $modulefilere:

$warn_msgs: Unable to find ModulesHelp in $modulefilere.
$modlin"

# test without module loaded
testouterr_cmd_re "sh" "help $module" "" $tserr

# test with module loaded
setenv_path_var TS1 "yes"
setenv_var TS2 "yes"
setenv_loaded_module $module $modulefile

testouterr_cmd_re "sh" "help $module" "" $tserr

# restore environment
unsetenv_path_var TS1
unsetenv_var TS2
unsetenv_loaded_module


#
#  test test mode
#

set tserr "$modlin
Module Specific Test for $modulefilere:

$warn_msgs: Unable to find ModulesTest in $modulefilere.
$modlin"

# test without module loaded
testouterr_cmd_re "sh" "test $module" "" $tserr

# test with module previously loaded
setenv_path_var TS1 "yes"
setenv_var TS2 "yes"
setenv_loaded_module $module $modulefile

testouterr_cmd_re "sh" "test $module" "" $tserr

# restore environment
unsetenv_path_var TS1
unsetenv_var TS2
unsetenv_loaded_module


#
#  Cleanup
#

unset tserr
unset ans

unset modulefilere
unset modulefile
unset module
