##############################################################################
#   Modules Revision 3.0
#   Providing a flexible user environment
#
#   File:		modules.50-cmds/%M%
#   Revision:		%I%
#   First Edition:	2017/05/25
#   Last Mod.:		%U%, %G%
#
#   Authors:		R.K. Owen, <rk@owen.sj.ca.us>
#
#   Description:	Testuite testsequence
#   Command:		load
#   Modulefiles:	remove/1.0
#   Sub-Command:
#
#   Comment:	%C{
#			Tests the 'remove-path' module subcommand with
#			an arbitrary delimiter
#		}C%
#
##############################################################################

#
#  Variables. This test forces a module load command. It will result in the
#    environment variables "_LMFILES_", "LOADEDMODULES" and "testsuite" to
#    be set up
#

set ts_1 "http://foobar.org"
set ts_2 "http://foobar.net"
set ts_3 "http://foobar.com"
set ts_new "$ts_1\\\\ $ts_2"
set ts_new2 "$ts_1 $ts_2"
# test colon char is correctly escaped in _modshare var
set tsmod_new "http\\\\\\\\://foobar.net:1:http\\\\\\\\://foobar.org:1"
set tsmod_new2 "http\\\\://foobar.net:1:http\\\\://foobar.org:1"
set env(testsuite)	"$ts_1 $ts_2 $ts_3"
set env(testsuite_modshare)	"http\\://foobar.org:1:http\\://foobar.net:1:http\\://foobar.com:1"
set module "remove/1.0"
set modulefile "$env(MODULEPATH)/$module"

#
#  For the different shells ...
#

set lmfmod_sh "_LMFILES__modshare=(.*); export _LMFILES__modshare;"
set lmmod_sh "LOADEDMODULES_modshare=(.*); export LOADEDMODULES_modshare;"
set tsmod_sh "testsuite_modshare=$tsmod_new; export testsuite_modshare;"
set lmf_sh "_LMFILES_=$modulefile; export _LMFILES_;"
set lm_sh "LOADEDMODULES=$module; export LOADEDMODULES;"
set ts_sh "testsuite=$ts_new; export testsuite;"

set lmfmod_csh "setenv _LMFILES__modshare (.*);"
set lmmod_csh "setenv LOADEDMODULES_modshare (.*);"
set tsmod_csh "setenv testsuite_modshare $tsmod_new;"
set lmf_csh "setenv _LMFILES_ $modulefile;"
set lm_csh "setenv LOADEDMODULES $module;"
set ts_csh "setenv testsuite $ts_new;"

set lmfmod_fish "set -xg _LMFILES__modshare (.*);"
set lmmod_fish "set -xg LOADEDMODULES_modshare (.*);"
set tsmod_fish "set -xg testsuite_modshare $tsmod_new;"
set lmf_fish "set -xg _LMFILES_ $modulefile;"
set lm_fish "set -xg LOADEDMODULES $module;"
set ts_fish "set -xg testsuite $ts_new;"

set lmfmod_tcl "set env\\\(_LMFILES__modshare\\\) \"(.*)\";"
set lmmod_tcl "set env\\\(LOADEDMODULES_modshare\\\) \"(.*)\";"
set tsmod_tcl "set env\\\(testsuite_modshare\\\) \"$tsmod_new2\";"
set lmf_tcl "set env\\\(_LMFILES_\\) \"$modulefile\";"
set lm_tcl "set env\\\(LOADEDMODULES\\\) \"$module\";"
set ts_tcl "set env\\\(testsuite\\\) \"$ts_new2\";"

set lmfmod_perl "\\\$ENV{\'_LMFILES__modshare\'} = \'(.*)\';"
set lmmod_perl "\\\$ENV{\'LOADEDMODULES_modshare\'} = \'(.*)\';"
set tsmod_perl "\\\$ENV{\'testsuite_modshare\'} = \'$tsmod_new2\';"
set lmf_perl "\\\$ENV{\'_LMFILES_\'} = \'$modulefile\';"
set lm_perl "\\\$ENV{\'LOADEDMODULES\'} = \'$module\';"
set ts_perl "\\\$ENV{\'testsuite\'} = \'$ts_new2\';"

set lmfmod_python "os.environ\\\[\'_LMFILES__modshare\'\\\] = \'(.*)\'"
set lmmod_python "os.environ\\\[\'LOADEDMODULES_modshare\'\\\] = \'(.*)\'"
set tsmod_python "os.environ\\\[\'testsuite_modshare\'\\\] = \'$tsmod_new2\'"
set lmf_python "os.environ\\\[\'_LMFILES_\'\\\] = \'$modulefile\'"
set lm_python "os.environ\\\[\'LOADEDMODULES\'\\\] = \'$module\'"
set ts_python "os.environ\\\[\'testsuite\'\\\] = \'$ts_new2\'"

set lmfmod_lisp "\\\(setenv \"_LMFILES__modshare\" \"(.*)\"\\\)"
set lmmod_lisp "\\\(setenv \"LOADEDMODULES_modshare\" \"(.*)\"\\\)"
set tsmod_lisp "\\\(setenv \"testsuite_modshare\" \"$tsmod_new2\"\\\)"
set lmf_lisp "\\\(setenv \"_LMFILES_\" \"$modulefile\"\\\)"
set lm_lisp "\\\(setenv \"LOADEDMODULES\" \"$module\"\\\)"
set ts_lisp "\\\(setenv \"testsuite\" \"$ts_new2\"\\\)"

#
#  The tests
#

test_cmd_re "sh" "load $module" "$lmfmod_sh\n$lmmod_sh\n$tsmod_sh\n$lmf_sh\n$lm_sh\n$ts_sh\$"
test_cmd_re "bash" "load $module" "$lmfmod_sh\n$lmmod_sh\n$tsmod_sh\n$lmf_sh\n$lm_sh\n$ts_sh\$"
test_cmd_re "ksh" "load $module" "$lmfmod_sh\n$lmmod_sh\n$tsmod_sh\n$lmf_sh\n$lm_sh\n$ts_sh\$"
test_cmd_re "zsh" "load $module" "$lmfmod_sh\n$lmmod_sh\n$tsmod_sh\n$lmf_sh\n$lm_sh\n$ts_sh\$"
test_cmd_re "csh" "load $module" "$lmfmod_csh\n$lmmod_csh\n$tsmod_csh\n$lmf_csh\n$lm_csh\n$ts_csh\$"
test_cmd_re "tcsh" "load $module" "$lmfmod_csh\n$lmmod_csh\n$tsmod_csh\n$lmf_csh\n$lm_csh\n$ts_csh\$"
test_cmd_re "fish" "load $module" "$lmfmod_fish\n$lmmod_fish\n$tsmod_fish\n$lmf_fish\n$lm_fish\n$ts_fish\$"
test_cmd_re "tcl" "load $module" "$lmfmod_tcl\n$lmmod_tcl\n$tsmod_tcl\n$lmf_tcl\n$lm_tcl\n$ts_tcl\$"
test_cmd_re "perl" "load $module" "$lmfmod_perl\n$lmmod_perl\n$tsmod_perl\n$lmf_perl\n$lm_perl\n$ts_perl\n1;\$"
test_cmd_re "python" "load $module" "import os\n$lmfmod_python\n$lmmod_python\n$tsmod_python\n$lmf_python\n$lm_python\n$ts_python\$"
test_cmd_re "lisp" "load $module" "$lmfmod_lisp\n$lmmod_lisp\n$tsmod_lisp\n$lmf_lisp\n$lm_lisp\n$ts_lisp\$"

#
#  Cleanup
#

unset env(testsuite)
unset env(testsuite_modshare)

unset ts_new
unset ts_new2
unset tsmod_new
unset tsmod_new2
unset ts_3
unset ts_2
unset ts_1

unset ts_sh
unset lm_sh
unset lmf_sh
unset tsmod_sh
unset lmmod_sh
unset lmfmod_sh

unset ts_csh
unset lm_csh
unset lmf_csh
unset tsmod_csh
unset lmmod_csh
unset lmfmod_csh

unset ts_fish
unset lm_fish
unset lmf_fish
unset tsmod_fish
unset lmmod_fish
unset lmfmod_fish

unset ts_tcl
unset lm_tcl
unset lmf_tcl
unset tsmod_tcl
unset lmmod_tcl
unset lmfmod_tcl

unset ts_perl
unset lm_perl
unset lmf_perl
unset tsmod_perl
unset lmmod_perl
unset lmfmod_perl

unset ts_python
unset lm_python
unset lmf_python
unset tsmod_python
unset lmmod_python
unset lmfmod_python

unset ts_lisp
unset lm_lisp
unset lmf_lisp
unset tsmod_lisp
unset lmmod_lisp
unset lmfmod_lisp

unset modulefile
unset module
