##############################################################################
#   Modules Revision 3.0
#   Providing a flexible user environment
#
#   File:		modules.50-cmds/%M%
#   Revision:		%I%
#   First Edition:	1995/12/06
#   Last Mod.:		%U%, %G%
#
#   Authors:		Jens Hamisch, Jens.Hamisch@Strawberry.COM
#
#   Description:	Testuite testsequence
#   Command:		load
#   Modulefiles:	info/name
#   Sub-Command:
#
#   Comment:	%C{
#			Tests the 'module-info name' module subcommand for all
#			allowed shell types.
#		}C%
#
##############################################################################

#
#  Variables. This test forces a module load command. It will result in the
#    environment variables "_LMFILES_", "LOADEDMODULES" and "testsuite" to
#    be set up
#

set module "info/name"
set modulefile "$env(MODULEPATH)/$module"

#
#  For the different shells ...
#

set lmf_sh "_LMFILES_=$modulefile ;export _LMFILES_;"
set lm_sh "LOADEDMODULES=$module ;export LOADEDMODULES;"
set ts_sh "testsuite=$module ;export testsuite;"

set lmf_csh "setenv _LMFILES_ $modulefile ;"
set lm_csh "setenv LOADEDMODULES $module ;"
set ts_csh "setenv testsuite $module ;"

set lmf_perl "\$ENV{'_LMFILES_'} = '$modulefile';"
set lm_perl "\$ENV{'LOADEDMODULES'} = '$module';"
set ts_perl "\$ENV{'testsuite'} = '$module';"

set lmf_cmake "set(ENV{_LMFILES_} \"$modulefile\")"
set lm_cmake "set(ENV{LOADEDMODULES} \"$module\")"
set ts_cmake "set(ENV{testsuite} \"$module\")"

#
#  The tests
#

test_cmd "sh" "load $module" "$lm_sh$lmf_sh$ts_sh"
test_cmd "ksh" "load $module" "$lm_sh$lmf_sh$ts_sh"
test_cmd "zsh" "load $module" "$lm_sh$lmf_sh$ts_sh"
test_cmd "csh" "load $module" "$lm_csh$lmf_csh$ts_csh"
test_cmd "tcsh" "load $module" "$lm_csh$lmf_csh$ts_csh"
test_cmd "perl" "load $module" "$lm_perl$lmf_perl$ts_perl"
test_cmd "cmake" "load $module" "$lm_cmake\n$lmf_cmake\n$ts_cmake"

#
#  Cleanup
#

unset ts_sh
unset lm_sh
unset lmf_sh

unset ts_csh
unset lm_csh
unset lmf_csh

unset ts_perl
unset lm_perl
unset lmf_perl

unset ts_cmake
unset lm_cmake
unset lmf_cmake

unset modulefile
unset module
