##############################################################################
#   Modules Revision 3.0
#   Providing a flexible user environment
#
#   File:		modules.50-cmds/%M%
#   Revision:		%I%
#   First Edition:	2017/11/28
#   Last Mod.:		%U%, %G%
#
#   Authors:		Xavier Delaruelle, xavier.delaruelle@cea.fr
#
#   Description:	Testuite testsequence
#   Command:		load
#   Modulefiles:	info/isavail
#   Sub-Command:
#
#   Comment:	%C{
#			Tests the 'is-avail' modulefile subcommand for all
#			allowed shell types.
#		}C%
#
##############################################################################

set module "info/isavail"
set modulefile "$modpath/$module"

#
#  The tests
#

lappend ans [list set testsuite1 0]
lappend ans [list set testsuite2 0]
lappend ans [list set testsuite3 0]
lappend ans [list set testsuite4 1]
lappend ans [list set testsuite5 [if_implicitdefault 1 0]]
lappend ans [list set testsuite6 1]
lappend ans [list setpath LOADEDMODULES $module]
lappend ans [list setpath _LMFILES_ $modulefile]

testouterr_cmd "ALL" "load $module" $ans ""

#
#  Cleanup
#

unset ans
unset modulefile
unset module
